/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampusPartnershipRouteImport } from './routes/campus-partnership'
import { Route as ConfidenceCoachRouteImport } from './routes/confidence-coach'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LocalizedIntelligenceRouteImport } from './routes/localized-intelligence'
import { Route as MarketMappingRouteImport } from './routes/market-mapping'
import { Route as MicroRoadmapRouteImport } from './routes/micro-roadmap'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyOcrRouteImport } from './routes/privacy-ocr'
import { Route as ResumeAnalysisRouteImport } from './routes/resume-analysis'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiAnalyzeResumeRouteImport } from './routes/api.analyze-resume'
import { Route as ApiCitySkillsRouteImport } from './routes/api.city-skills'
import { Route as ApiCoachChatRouteImport } from './routes/api.coach-chat'
import { Route as ApiCompareResumesRouteImport } from './routes/api.compare-resumes'
import { Route as ApiGenerateRoadmapRouteImport } from './routes/api.generate-roadmap'
import { Route as ApiJobsRouteImport } from './routes/api.jobs'
import { Route as ApiMarketTrendRouteImport } from './routes/api.market-trend'
import { Route as ApiTailorResumeRouteImport } from './routes/api.tailor-resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusPartnershipRoute = CampusPartnershipRouteImport.update({
  id: '/campus-partnership',
  path: '/campus-partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidenceCoachRoute = ConfidenceCoachRouteImport.update({
  id: '/confidence-coach',
  path: '/confidence-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizedIntelligenceRoute = LocalizedIntelligenceRouteImport.update({
  id: '/localized-intelligence',
  path: '/localized-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketMappingRoute = MarketMappingRouteImport.update({
  id: '/market-mapping',
  path: '/market-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroRoadmapRoute = MicroRoadmapRouteImport.update({
  id: '/micro-roadmap',
  path: '/micro-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyOcrRoute = PrivacyOcrRouteImport.update({
  id: '/privacy-ocr',
  path: '/privacy-ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalysisRoute = ResumeAnalysisRouteImport.update({
  id: '/resume-analysis',
  path: '/resume-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeResumeRoute = ApiAnalyzeResumeRouteImport.update({
  id: '/api/analyze-resume',
  path: '/api/analyze-resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitySkillsRoute = ApiCitySkillsRouteImport.update({
  id: '/api/city-skills',
  path: '/api/city-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachChatRoute = ApiCoachChatRouteImport.update({
  id: '/api/coach-chat',
  path: '/api/coach-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompareResumesRoute = ApiCompareResumesRouteImport.update({
  id: '/api/compare-resumes',
  path: '/api/compare-resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoadmapRoute = ApiGenerateRoadmapRouteImport.update({
  id: '/api/generate-roadmap',
  path: '/api/generate-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketTrendRoute = ApiMarketTrendRouteImport.update({
  id: '/api/market-trend',
  path: '/api/market-trend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTailorResumeRoute = ApiTailorResumeRouteImport.update({
  id: '/api/tailor-resume',
  path: '/api/tailor-resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/campus-partnership': typeof CampusPartnershipRoute
  '/confidence-coach': typeof ConfidenceCoachRoute
  '/dashboard': typeof DashboardRoute
  '/localized-intelligence': typeof LocalizedIntelligenceRoute
  '/market-mapping': typeof MarketMappingRoute
  '/micro-roadmap': typeof MicroRoadmapRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-ocr': typeof PrivacyOcrRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/terms': typeof TermsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/analyze-resume': typeof ApiAnalyzeResumeRoute
  '/api/city-skills': typeof ApiCitySkillsRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/api/compare-resumes': typeof ApiCompareResumesRoute
  '/api/generate-roadmap': typeof ApiGenerateRoadmapRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/market-trend': typeof ApiMarketTrendRoute
  '/api/tailor-resume': typeof ApiTailorResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/campus-partnership': typeof CampusPartnershipRoute
  '/confidence-coach': typeof ConfidenceCoachRoute
  '/dashboard': typeof DashboardRoute
  '/localized-intelligence': typeof LocalizedIntelligenceRoute
  '/market-mapping': typeof MarketMappingRoute
  '/micro-roadmap': typeof MicroRoadmapRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-ocr': typeof PrivacyOcrRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/terms': typeof TermsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/analyze-resume': typeof ApiAnalyzeResumeRoute
  '/api/city-skills': typeof ApiCitySkillsRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/api/compare-resumes': typeof ApiCompareResumesRoute
  '/api/generate-roadmap': typeof ApiGenerateRoadmapRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/market-trend': typeof ApiMarketTrendRoute
  '/api/tailor-resume': typeof ApiTailorResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/campus-partnership': typeof CampusPartnershipRoute
  '/confidence-coach': typeof ConfidenceCoachRoute
  '/dashboard': typeof DashboardRoute
  '/localized-intelligence': typeof LocalizedIntelligenceRoute
  '/market-mapping': typeof MarketMappingRoute
  '/micro-roadmap': typeof MicroRoadmapRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-ocr': typeof PrivacyOcrRoute
  '/resume-analysis': typeof ResumeAnalysisRoute
  '/terms': typeof TermsRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/analyze-resume': typeof ApiAnalyzeResumeRoute
  '/api/city-skills': typeof ApiCitySkillsRoute
  '/api/coach-chat': typeof ApiCoachChatRoute
  '/api/compare-resumes': typeof ApiCompareResumesRoute
  '/api/generate-roadmap': typeof ApiGenerateRoadmapRoute
  '/api/jobs': typeof ApiJobsRoute
  '/api/market-trend': typeof ApiMarketTrendRoute
  '/api/tailor-resume': typeof ApiTailorResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/campus-partnership'
    | '/confidence-coach'
    | '/dashboard'
    | '/localized-intelligence'
    | '/market-mapping'
    | '/micro-roadmap'
    | '/opportunities'
    | '/privacy'
    | '/privacy-ocr'
    | '/resume-analysis'
    | '/terms'
    | '/api/agent'
    | '/api/analyze-resume'
    | '/api/city-skills'
    | '/api/coach-chat'
    | '/api/compare-resumes'
    | '/api/generate-roadmap'
    | '/api/jobs'
    | '/api/market-trend'
    | '/api/tailor-resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/auth'
    | '/campus-partnership'
    | '/confidence-coach'
    | '/dashboard'
    | '/localized-intelligence'
    | '/market-mapping'
    | '/micro-roadmap'
    | '/opportunities'
    | '/privacy'
    | '/privacy-ocr'
    | '/resume-analysis'
    | '/terms'
    | '/api/agent'
    | '/api/analyze-resume'
    | '/api/city-skills'
    | '/api/coach-chat'
    | '/api/compare-resumes'
    | '/api/generate-roadmap'
    | '/api/jobs'
    | '/api/market-trend'
    | '/api/tailor-resume'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/auth'
    | '/campus-partnership'
    | '/confidence-coach'
    | '/dashboard'
    | '/localized-intelligence'
    | '/market-mapping'
    | '/micro-roadmap'
    | '/opportunities'
    | '/privacy'
    | '/privacy-ocr'
    | '/resume-analysis'
    | '/terms'
    | '/api/agent'
    | '/api/analyze-resume'
    | '/api/city-skills'
    | '/api/coach-chat'
    | '/api/compare-resumes'
    | '/api/generate-roadmap'
    | '/api/jobs'
    | '/api/market-trend'
    | '/api/tailor-resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  CampusPartnershipRoute: typeof CampusPartnershipRoute
  ConfidenceCoachRoute: typeof ConfidenceCoachRoute
  DashboardRoute: typeof DashboardRoute
  LocalizedIntelligenceRoute: typeof LocalizedIntelligenceRoute
  MarketMappingRoute: typeof MarketMappingRoute
  MicroRoadmapRoute: typeof MicroRoadmapRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyOcrRoute: typeof PrivacyOcrRoute
  ResumeAnalysisRoute: typeof ResumeAnalysisRoute
  TermsRoute: typeof TermsRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiAnalyzeResumeRoute: typeof ApiAnalyzeResumeRoute
  ApiCitySkillsRoute: typeof ApiCitySkillsRoute
  ApiCoachChatRoute: typeof ApiCoachChatRoute
  ApiCompareResumesRoute: typeof ApiCompareResumesRoute
  ApiGenerateRoadmapRoute: typeof ApiGenerateRoadmapRoute
  ApiJobsRoute: typeof ApiJobsRoute
  ApiMarketTrendRoute: typeof ApiMarketTrendRoute
  ApiTailorResumeRoute: typeof ApiTailorResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-partnership': {
      id: '/campus-partnership'
      path: '/campus-partnership'
      fullPath: '/campus-partnership'
      preLoaderRoute: typeof CampusPartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidence-coach': {
      id: '/confidence-coach'
      path: '/confidence-coach'
      fullPath: '/confidence-coach'
      preLoaderRoute: typeof ConfidenceCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localized-intelligence': {
      id: '/localized-intelligence'
      path: '/localized-intelligence'
      fullPath: '/localized-intelligence'
      preLoaderRoute: typeof LocalizedIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-mapping': {
      id: '/market-mapping'
      path: '/market-mapping'
      fullPath: '/market-mapping'
      preLoaderRoute: typeof MarketMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micro-roadmap': {
      id: '/micro-roadmap'
      path: '/micro-roadmap'
      fullPath: '/micro-roadmap'
      preLoaderRoute: typeof MicroRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-ocr': {
      id: '/privacy-ocr'
      path: '/privacy-ocr'
      fullPath: '/privacy-ocr'
      preLoaderRoute: typeof PrivacyOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analysis': {
      id: '/resume-analysis'
      path: '/resume-analysis'
      fullPath: '/resume-analysis'
      preLoaderRoute: typeof ResumeAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-resume': {
      id: '/api/analyze-resume'
      path: '/api/analyze-resume'
      fullPath: '/api/analyze-resume'
      preLoaderRoute: typeof ApiAnalyzeResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/city-skills': {
      id: '/api/city-skills'
      path: '/api/city-skills'
      fullPath: '/api/city-skills'
      preLoaderRoute: typeof ApiCitySkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach-chat': {
      id: '/api/coach-chat'
      path: '/api/coach-chat'
      fullPath: '/api/coach-chat'
      preLoaderRoute: typeof ApiCoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compare-resumes': {
      id: '/api/compare-resumes'
      path: '/api/compare-resumes'
      fullPath: '/api/compare-resumes'
      preLoaderRoute: typeof ApiCompareResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-roadmap': {
      id: '/api/generate-roadmap'
      path: '/api/generate-roadmap'
      fullPath: '/api/generate-roadmap'
      preLoaderRoute: typeof ApiGenerateRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market-trend': {
      id: '/api/market-trend'
      path: '/api/market-trend'
      fullPath: '/api/market-trend'
      preLoaderRoute: typeof ApiMarketTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tailor-resume': {
      id: '/api/tailor-resume'
      path: '/api/tailor-resume'
      fullPath: '/api/tailor-resume'
      preLoaderRoute: typeof ApiTailorResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  CampusPartnershipRoute: CampusPartnershipRoute,
  ConfidenceCoachRoute: ConfidenceCoachRoute,
  DashboardRoute: DashboardRoute,
  LocalizedIntelligenceRoute: LocalizedIntelligenceRoute,
  MarketMappingRoute: MarketMappingRoute,
  MicroRoadmapRoute: MicroRoadmapRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyOcrRoute: PrivacyOcrRoute,
  ResumeAnalysisRoute: ResumeAnalysisRoute,
  TermsRoute: TermsRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiAnalyzeResumeRoute: ApiAnalyzeResumeRoute,
  ApiCitySkillsRoute: ApiCitySkillsRoute,
  ApiCoachChatRoute: ApiCoachChatRoute,
  ApiCompareResumesRoute: ApiCompareResumesRoute,
  ApiGenerateRoadmapRoute: ApiGenerateRoadmapRoute,
  ApiJobsRoute: ApiJobsRoute,
  ApiMarketTrendRoute: ApiMarketTrendRoute,
  ApiTailorResumeRoute: ApiTailorResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
